integrations:
  # squad-huggingface:
  #   type: dataset
  #   ref: paperspace/dsn5wmo5xkgyqug:e7pc9wn
  # conll2003-huggingface:
  #   type: dataset
  #   ref: paperspace/dsv8sflblahlk5a:sle9lnd
  # imagefolder-huggingface:
  #   type: dataset
  #   ref: paperspace/dsffgua8bwc0kar:q3cz78h
  # superb-huggingface:
  #   type: dataset
  #   ref: paperspace/dsuo04ok5m0xlbt:mc9gtb6
  # swag-huggingface:
  #   type: dataset
  #   ref: paperspace/dsuvlmj7kz672io:2x9id6x
  # xsum-huggingface:
  #   type: dataset
  #   ref: paperspace/ds0d117a65azqrc:6a4r0v4
  # wmt16-huggingface:
  #   type: dataset
  #   ref: paperspace/dsvb67pd37d582q:z1vk5xn
  # wikitext-huggingface:
  #   type: dataset
  #   ref: paperspace/ds1swj6fp1w93ww:d4gphuz
  # librispeech_asr-huggingface:
  #   type: dataset
  #   ref: paperspace/dsrmuac2fm5juiz:dmj9o0j
  # glue-huggingface:
  #   type: dataset
  #   ref: paperspace/ds30bjcgo4467mz:29gw3mu
  exe_cache-huggingface:
    type: dataset
    ref: paperspace/dsiv2opoyjygwyu:f5qufgc